### ISSUE TITLE
MIntO with only Meta-transcriptomics data

### ISSUE THREAD

**Issue by sarpiens** [arumugamlab/MIntO#8]
Hello,

I was interested in using your pipeline for a meta-transcriptomics analysis that I'm preparing. However, I do not have any meta-genomic data. I was wondering if I could still use your pipeline to process only meta-transcriptomic data? If so, could you please give me some pointers on which mode should I use and any considerations that I should take into account in this particular case?

Thanks in advance!
Best regards

**Comment by arumugamlab** [comment]
Hello,

Yes, this is possible in theory. It does come with some constraints though. The main limitation is this: to use metatranscriptomic (metaT) data by itself, MIntO (i) needs to know which "genome" each gene belongs to, and (ii) needs to know the 10 marker genes from that genome. Then it can normalize the expression level of a given gene against the "housekeeping" background and you have now removed the confounding effect of the abundance of that species. You could provide this information via (i) reference genomes, or (ii) MAGs generated from your own metaT data. Both have pluses and minuses. And MIntO can help you with both. 

Some thoughts on the two approaches:
**1. Reference genomes:** These may not represent your samples very well. but if they do, then that's your best bet. 
**2. Generating MAGs from metaT data:** This is also tricky because contigs will not get too long as reads won't cover intergenic regions. When you only have short contigs (often maximum 100k bp), it is also not easy to get many high-quality MAGs. However, if you have numerous samples (say >50 or better >100), you increase the number of high-quality MAGs. 

To give you the best advice, I would need to know characteristics of your samples, sequencing depth, number of samples and whether there are repeated samples. If you could share some more information, we can discuss further and chart a good plan.

Best wishes,
Mani

**Comment by sarpiens** [comment]
Hello Mani,

Thanks for you quick response. We have 6 sheep rumen fluid samples with metatranscriptomics data (twp for each condition), no technical replicates were generated, PAIRED Fastqs. After applying quality control steps (filtering and trimming reads, host filtering and rRNA filtering), they have a sequencing depth of more than 30 million reads (raw sequencing depth around 40 million reads). In our case, what would be the most recommendable approach?

Thanks in advance!
Best regards

**Comment by arumugamlab** [comment]
Closing as there was no feedback or follow up. Please reopen if it continues to be an issue.
